import img from "../Assets/bgimg.jpg";
import img1 from "../Assets/logo.avif";
export const cardData = [
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "25 feb ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
  {
    CardTitle: "Card title!",
    heading: "he choose?If a dog chews shoes whose shoes does he choose?",
    heading2: "he choose?If a dog chews shoes whose shoes does he choose?",
    date: "27 jan ,2024",
    time: "11:23 AM",
    image: img,
  },
];
